// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","id":"1"},"2":{"path":"/login","id":"2"},"3":{"path":"","id":"3"},"4":{"path":"home","meta":{"title":"首页"},"parentId":"3","id":"4"},"5":{"path":"feature1","meta":{"title":"功能1"},"parentId":"3","id":"5"},"6":{"path":"feature2","meta":{"title":"功能2"},"parentId":"3","id":"6"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "layout__index" */'@/layout/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__feature1__index" */'@/pages/feature1/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__feature2__index" */'@/pages/feature2/index.tsx')),
},
  };
}
